# Generated by Django 5.2.13 on 2026-04-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportnode',
            old_name='left_distanc',
            new_name='left_distance',
        ),
    ]
